using ClubModels.Models.GeneralCodes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Formats.Asn1.AsnWriter;

namespace ClubModels.Configuration.GeneralCodes
{
    public class SectionCodesConfiguration : IEntityTypeConfiguration<SectionCode>
    {
        public void Configure(EntityTypeBuilder<SectionCode> builder)
        {
            builder.HasData(
                new SectionCode { Id = Guid.NewGuid(), Code = 1, Name = "عضوية زائرة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 2, Name = "رئيس مجس الإدارة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 6, Name = "رئاسة الهيئة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 7, Name = "ورش", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 8, Name = "مطابع", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 3, Name = "معاشات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 4, Name = "مستشار الوزير", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 5, Name = "مترو", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 9, Name = "ابو زعبل", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 10, Name = "التبين", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 11, Name = "ديزل القاهره", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 12, Name = "فرز القاهره", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 13, Name = "هندسه السكه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 14, Name = "منطقه القاهره", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 15, Name = "حركه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 21, Name = "الوحدات المتحركة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 16, Name = "عباسية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 20, Name = "بولاق الدكرور", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 25, Name = "الاشارات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 26, Name = "المركز الطبي", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 27, Name = "ادارة مالية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 28, Name = "الخدمات المشتركه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 29, Name = "ادارة المحطات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 30, Name = "المنشأت", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 31, Name = "الكبارى", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 32, Name = "التشغيل", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 33, Name = "المسافات الطويلة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 34, Name = "المسافات القصيرة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 35, Name = "خدمه العملاء", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 40, Name = "ابي غاطس", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 41, Name = "د.طرة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 42, Name = "د.بولاق", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 43, Name = "السلامه و الجوده", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 44, Name = "مخازن", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 52, Name = "مخازن", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 54, Name = "مخازن", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 61, Name = "ابى غاطس", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 63, Name = "مراقب ابراج", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 64, Name = "الموارد البشرية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 70, Name = "البنيه الاساسيه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 0, Name = "0", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 73, Name = "كهرباء السبتية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 75, Name = "قطاع البضائع", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 76, Name = "دعم فنى", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 77, Name = "ديزل كوبري الليمون", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 79, Name = "عربات الركاب", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 80, Name = "سيارات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 83, Name = "ابو راضى", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 84, Name = "المعدات الثقيلة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 85, Name = "شئون قانونيه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 86, Name = "اداره النقل", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 87, Name = "عنابر بولاق", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 89, Name = "الاملاك", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 93, Name = "الفحص", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 94, Name = "قطاع الصيانه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 95, Name = "حاسب الى", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 99, Name = "مبيعات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 74, Name = "الادارة المركزية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 60, Name = "نائب رئيس مجلس إداره", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 17, Name = "م.الالكتروني", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 55, Name = "اداره التنسيق", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 24, Name = "مدير هيئة سابق", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 71, Name = "بنك القاهرة", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 18, Name = "المشروعات والتطوير", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 51, Name = "مؤقته", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 66, Name = "اداره السيارات", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 19, Name = "موسميه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 90, Name = "ديزل الزقازيق", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 50, Name = "الادارة القانونية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 88, Name = "اداره الهيئه", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false },
                new SectionCode { Id = Guid.NewGuid(), Code = 81, Name = "رئيس الشئون القانونية", Annual = false, Improve = false, IsId = false, Init = false, Office = false, Penalty = false, Player = false, Pool = false, Post = false, Reg = false, River = false, Stamp = false, Worker = false, Donation = false, Maintenance = false, Society = false, ComPenalty = false, ReserveFee = false }
                );
        }
    }
}
